module.exports = {
    US: 'US',
    ALL: 'ALL',
    CHAT: 'chat',
    MOCK: 'mock',
    DARK: 'dark',
    USERS: 'users',
    REDIS: 'redis',
    MYSQL: 'mysql',
    MONGO: 'mongo',
    LIGHT: 'light',
    PUBLIC: 'PUBLIC',
    ONLINE: 'online',
    MESSAGE: 'message',
    OFFLINE: 'offline',
    PRIVATE: 'PRIVATE',
    SETTINGS: 'settings',
    POSTGRES: 'postgres',
    CONNECTION: 'connection',
    DISCONNECT: 'disconnect',
    LOCALHOST: 'http://localhost:8080',
};